[package]
name = "idevice-ffi"
version = "0.1.0"
edition = "2024"


[dependencies]
idevice = { path = "../idevice", features = ["full"] }
log = "0.4.26"
simplelog = "0.12.2"
once_cell = "1.21.1"
tokio = { version = "1.44.1", features = ["full"] }
libc = "0.2.171"
openssl-sys = { version = "0.9", features = ["vendored"] }
plist = "1.7.1"
plist_plus = { version = "0.2.6", features = ["dynamic"] }

[build-dependencies]
cbindgen = "0.28.0"

[lib]
crate-type = ["staticlib"]
